let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 1
let problemSetNumber = 3
let test = SAT
let subject = Mathematics
let category = Passport to Advanced Math/Equivalent expressions
let difficulty = 2
let question = Which of the following polynomials is equivalent to the expression above?
let choices = -3x^2 + 2x - 6, -3x^2 + 10x - 6, 5x^2 + 2x - 6, 5x^2 + 10x - 6
let answer = B
let solution = Expand the multiplied terms in the given expression and collect like powers of~$x$: \par \begin {align*} x(x+3) - 4x(x-1) + 3(x-2) &= \left (x^2+3x\right )-\left (4x^2-4x\right )+\left (3x-6\right ) \\ &= x^2+3x-4x^2+4x+3x-6 \\ &= \left (x^2-4x^2\right )+(3x+4x+3x)-6 \\ &= -3x^2+10x-6 \\ \end {align*}
let diagram = $x(x+3) - 4x(x-1) + 3(x-2)$
let choicesAlign = M
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null