let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 14
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Heart of Algebra/Linear equations in two variables
let difficulty = 3
let question = Which of the following is the best interpretation of the $y$‑intercept of the line of best fit?
let choices = ['The actual number of electric utility coal power plants in the United States in~2006.', 'The predicted number of electric utility coal power plants in the United States in~2006.', 'The actual number of electric utility coal power plants in the United States built before~2006.', 'The predicted number of electric utility coal power plants in the United States built before~2006.']
let answer = B
let solution = The line of best fit gives predicted values, not actual values. The actual values are given by the points on the graph. Since the graph depicts the number of electric utility coal power plants in the United States, choice~\TextChoice {2} is correct. (Choices \TextChoice {3} and~\TextChoice {4} are incorrect because the graph does not tell us when coal power plants were built.)
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null