let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 15
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Heart of Algebra/Linear equations in one variable
let difficulty = 3
let question = At a sporting goods store, each baseball weighs 5.25~ounces, and each softball weight $w$~more ounces than each baseball. A display case at the store contains 10~baseballs and 10~softballs, and the total weight of the baseballs and softballs in the case is 120~ounces. What is the value of~$w$?
let choices = 0.85,1.20,1.25,1.50
let answer = D
let solution = The weight of each softball is $5.25+w$~ounces, so the weight of 10~baseballs and 10~softballs is $10(5.25)+10(5.25+w)$~ounces. The question says that this weight is 120~ounces, so we can solve for~$w$: \par \begin {align*} 10(5.25)+10(5.25+w) &= 120 \\ 52.5+52.5+10w &= 120 \\ 105 + 10w &= 120 \\ 10w &= 15 \\ w &= 1.5 \end {align*} \par Choice~\TextChoice {4} is correct.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null