let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 11
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Evaluating statistical claims: observational studies and experiments
let difficulty = 3
let question = To determine the number of recent graduates of a college who plan to start working within the next four weeks, Esteban surveyed 80~recent graduates of the college at an on-campus job fair. Of those surveyed, 90~percent plan to start working within the next four weeks. Which of the following statements must be true?
let choices = ['Of the recent graduates of the college, 90~percent plan to start working within the next four weeks.', 'Of the recent graduates of the college, 90~percent will be working in four weeks.', 'The sample size is too small to draw a reliable conclusion.', 'No prediction should be made because of the location the survey was given.']
let answer = D
let solution = The survey was conducted to determine the number of recent graduates who plan to start working within the next four weeks. Those graduates at a job fair are likely to be actively seeking work, so the location the survey was conducted will likely produce biased results. Thus, choice~\TextChoice {4} is correct. \par Choice~\TextChoice {1} is incorrect because of the reason mentioned above; we cannot draw a reliable conclusion based on the location of the survey. Choice~\TextChoice {2} is incorrect because graduates planning to start working within the next four weeks will not necessarily be working in four weeks time. Choice~\TextChoice {3} is incorrect because the sample size of 80~students is sufficient to produce an estimate, as long as the 80~students are randomly selected from the population.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null