let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 20
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Percentages
let difficulty = 3
let question = What percent of the participants guessed under the correct value for jar~A?
let choices = 18,30,52,56
let answer = C
let solution = We can add the numbers in the table to find that there were 50~total participants. Of those~50, a total of~19 guessed under the correct value for jar~A and under the correct value for jar~B, and a total of~7 guessed under the correct value for jar~A and over the correct value for jar~B. Thus, $19+7=26$~participants guessed under the correct value for jar~A. Since 26 is 52\% of~50, choice~\TextChoice {3} is correct.
let diagram = \begin {tabular}{|c|c|z{2}|z{2}|} \hline \multicolumn {1}{|c}{} & & \multicolumn {2}{c|}{Jar~A} \\ \cline {3-4} \multicolumn {1}{|c}{} & & \multicolumn {1}{c|}{Under} & \multicolumn {1}{c|}{Over} \\ \hline \multirow {2}{*}{Jar~B} & Under & 19 & 9 \\ \cline {2-4} {} & Over & 7 & 15 \\ \hline \end {tabular}
let choicesAlign = r<{\%}
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = In a contest, participants guessed the number of coins in each of two jars. Nobody guessed the correct number of coins in either jar, and the contest designers recorded the number of participants who guessed under or over the correct values for each jar in the table below.
let percent_correct = null