let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 23
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Two-variable data: models and scatterplots
let difficulty = 3
let question = Which of the following describes a linear relationship between the pair of variables listed?
let choices = ['The number of bacteria in a culture,~$n$, doubles each hour~$h$.', 'For every 10~years~$t$, the total volume of a glacial ridge~$V$ decreases by~1.5\\%.', 'Every million years~$m$, the diameter of a star increases by~0.02\\%.', 'Each second~$s$, the speed~$p$ of an object increases at a constant rate of 32~feet per second.']
let answer = D
let solution = In choice~\TextChoice {1}, the number of bacteria doubles each hour, so the growth is exponential, not linear. In choice~\TextChoice {2}, the volume decreases by a percentage every 10~years, representing an exponential decay of the volume. In choice~\TextChoice {3}, the diameter increases by a percentage every million years, representing an exponential growth of the diameter. In choice~\TextChoice {4}, the speed increases at a \emph {constant} rate, so the growth is linear.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null