let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 35
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Heart of Algebra/Systems of two linear equations in two variables
let difficulty = 3
let question = A grocery store sells orange juice in 1‑quart containers and 1‑gallon containers. The price of each 1‑quart container is~\$3, and the price of each 1‑gallon container is~\$7. One day, the grocery store sold 40~more 1‑quart containers than 1‑gallon containers for a total price of~\$230. How many containers of orange juice did the grocery store sell that day?
let choices = null
let answer = 62
let solution = Let $q$ be the number of 1‑quart containers and $g$ be the number of 1‑gallon containers. Since 40~more 1‑quart containers than 1‑gallon containers were sold, we know that~$q=g+40$, or~$q-g=40$. Given that the price of each 1‑quart container is~\$3 and the price of each 1‑gallon container is~\$7, the total price of the containers sold is~$3q+7g$, so~$3q+7g=230$. We have the following system of equations: \par \begin {align*} q-g &= 40 \\ 3q+7g &= 230 \\ \end {align*} \par Multiply the first equation by~7 and add to the second equation to get~$10q=510$. Thus,~$q=51$, so~$g=11$. The total number of containers sold that day is~$11+51=62$.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null