let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 38
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Percentages
let difficulty = 5
let question = The greatest distance between Venus and the Sun is 27.7~percent less than the greatest distance between Earth and the Sun, and the time it takes Venus to complete one orbit is 38.5~percent less than the time it takes Earth to complete one orbit. Based on the given equation, to the nearest tenth of a percent, the mean orbital speed of Venus is what percent greater than the mean orbital speed of Earth?
let choices = null
let answer = 17.6
let solution = We do not need to calculate any actual speeds to find the desired percentage. If $d$ is the greatest distance between Earth and the Sun, and $T$ is the time it takes Earth to complete one orbit, we know that the mean orbital speed is given by~$v=\frac {2\pi d}{T}$. For Venus, the greatest distance to the Sun is~$0.723d$, and the time it takes to complete one orbit is~$0.625T$. Using this information, the mean orbital speed of Venus is~$\frac {2\pi (0.723d)}{0.625T} = \frac {2\pi d}{T} \cdot \frac {0.723}{0.625}$. Since~$\frac {0.723}{0.625} \approx 1.176$, the mean orbital speed of Venus is approximately 17.6~percent greater than the mean orbital speed of Earth.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null