let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 32
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Passport to Advanced Math/Equivalent expressions
let difficulty = 2
let question = If~$x>2$, what is the value of~$\frac {4x^2-16}{(x+2)(x-2)}$?
let choices = null
let answer = 4
let solution = We can factor~4 from the numerator to rewrite the given expression as~$\frac {4(x^2-4)}{(x+2)(x-2)}$. We can further factor the numerator to get~$\frac {4(x+2)(x-2)}{(x+2)(x-2)}$. Note that this expression is undefined when the denominator is equal to~0. But we know that~$x>2$, so we can safely assume that $x+2$ and~$x-2$ are nonzero. Thus, we can cancel these terms in the numerator and denominator, and we are left with the value~4.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null