let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 34
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/One-variable data: distributions and measures of center and spread
let difficulty = 2
let question = The table above shows the distribution of the number of computers in the households of 20~students in a class. What is the median number of computers per household for the 20~students?
let choices = null
let answer = 4
let solution = The median of the 20~numbers is the average of the 10th and 11th~numbers when all 20~numbers are listed in increasing order. The first number is~1, the second through fourth numbers are~2, the fifth through eighth numbers are~3, and the ninth through 14th~numbers are~4. Thus, the 10th and 11th~numbers are both~4, so the median is~4.
let diagram = \begin {tabular}{|z{1}|z{1}|} \hline \multicolumn {1}{|c|}{Number of computers} & \multicolumn {1}{c|}{Frequency} \\ \hline 1 & 1 \\ \hline 2 & 3 \\ \hline 3 & 3 \\ \hline 4 & 7 \\ \hline 5 & 6 \\ \hline \end {tabular}
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null