let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 36
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Ratios, rates, proportional relationships, and units
let difficulty = 2
let question = The table above shows the distribution of Egyptian pyramids from the Fourth through Sixth dynasties by dynasty and volume. Based on the information in the table, what fraction of the pyramids from the Third and Fourth dynasties have a volume of more than \num {200000}~cubic meters?
let choices = null
let answer = $\frac {7}{10}$; 0.7
let solution = There are at total of 3~pyramids from the Third Dynasty and 7~pyramids from the Fourth Dynasty, so there are 10~total pyramids from these two dynasties. Of those pyramids, a total of~2 have a volume between \num {200000}~cubic meters and \num {500000}~cubic meters, and 5~have a volume of at least \num {500000}~cubic meters. Thus, a total of~7 pyramids have volumes of more than \num {200000}~cubic meters, so $\frac {7}{10}$~of the pyramids from these two dynasties have volumes of more than \num {200000}~cubic meters.
let diagram = Dynasty and Volume of Egyptian Pyramids from the Third Through Sixth Dynasties \par \medskip \par \begin {tabular}{|l|z{1}|z{1}|z{1}|} \hline {} & \multicolumn {3}{c|}{Volume (thousands of cubic meters)} \\ \cline {2-4} \multicolumn {1}{|c|}{Dynasty} & \multicolumn {1}{>{\centering \arraybackslash }m{4em}|}{At most 200} & \multicolumn {1}{>{\centering \arraybackslash }m{5em}|}{Between 200 and~500} & \multicolumn {1}{>{\centering \arraybackslash }m{4em}|}{At least 500} \\ \hline Third & 2 & 1 & 0 \\ \hline Fourth & 1 & 1 & 5 \\ \hline Fifth & 5 & 1 & 0 \\ \hline Sixth & 4 & 0 & 0 \\ \hline \end {tabular}
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null