let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 4
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Two-variable data: models and scatterplots
let difficulty = 2
let question = During a snow storm, snow fell for eight hours. The snow initially fell rapidly and accumulated on the ground but then fell more slowly as the storm went on. The height of the accumulated snow was measured each hour during the storm. Which of the following graphs could represent the total accumulated height of the snow from the storm during the eight hours?
let choices = ['\\begin {tikzpicture}[inline] \\begin {axis}[width=4.25cm, height=4.25cm, xlabel={Time (hours)}, ylabel={Snow height (inches)}, xmin=0, xmax=8, xtick={0,2,...,8}, ymin=0, ymax=16, ytick={0,4,...,16}, grid=major ] \\addplot [only marks, mark=*] coordinates {(0,0.00) (1,5.20) (2,8.67) (3,10.98) (4,12.52) (5,13.55) (6,14.23) (7,14.69) (8,15.00) }; \\end {axis} \\end {tikzpicture}', '\\begin {tikzpicture}[inline] \\begin {axis}[width=4.25cm, height=4.25cm, xlabel={Time (hours)}, ylabel={Snow height (inches)}, xmin=0, xmax=8, xtick={0,2,...,8}, ymin=0, ymax=16, ytick={0,4,...,16}, grid=major ] \\addplot [only marks, mark=*] coordinates {(0,15.00) (1,9.80) (2,6.33) (3,4.02) (4,2.48) (5,1.44) (6,0.77) (7,0.31) (8,0.00) }; \\end {axis} \\end {tikzpicture}', '\\begin {tikzpicture}[inline] \\begin {axis}[width=4.25cm, height=4.25cm, xlabel={Time (hours)}, ylabel={Snow height (inches)}, xmin=0, xmax=8, xtick={0,2,...,8}, ymin=0, ymax=16, ytick={0,4,...,16}, grid=major ] \\addplot [only marks, mark=*] coordinates {(0,0.00) (1,0.31) (2,0.77) (3,1.44) (4,2.48) (5,4.02) (6,6.99) (7,9.80) (8,15.00) }; \\end {axis} \\end {tikzpicture}', '\\begin {tikzpicture}[inline] \\begin {axis}[width=4.25cm, height=4.25cm, xlabel={Time (hours)}, ylabel={Snow height (inches)}, xmin=0, xmax=8, xtick={0,2,...,8}, ymin=0, ymax=16, ytick={0,4,...,16}, grid=major ] \\addplot [only marks, mark=*] coordinates {(0,0.00) (1,1.875) (2,3.75) (3,5.625) (4,7.5) (5,9.375) (6,11.25) (7,13.125) (8,15.0) }; \\end {axis} \\end {tikzpicture}']
let answer = A
let solution = Based on the situation described, the height of the snow must increase, rapidly at first, and then gradually more slowly. So we are looking for an increasing graph with rapid growth near 0~hours and slower growth near 8~hours. Such a graph is given in choice~\TextChoice {1}. \par Choice~\TextChoice {2} is incorrect because the graph is decreasing, not increasing. Choice~\TextChoice {3} is incorrect because the rate at which the height increases is slower initially, not faster initially. Choice~\TextChoice {4} is incorrect because the rate at which the height increases is constant, not fast and then slow.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null