let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 5
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Percentages
let difficulty = 2
let question = Alvin starts reading a 325‑page book and reads 4\% of the pages in the book each day until he has read all 325~pages. How many pages has Alvin read after 6~days?
let choices = 24,40,54,78
let answer = D
let solution = Alvin reads 4\% of the pages each day. Since there are 325~pages in the book, 4\% of the pages is~13. Thus, after 6~days, he has read $6(13)=78$~pages.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null