let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 7
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/Ratios, rates, proportional relationships, and units
let difficulty = 3
let question = How much less energy, in joules, is used by the new refrigerator than the old refrigerator in one \uline {minute}?
let choices = 5520,6480,7560,14040
let answer = B
let solution = The power consumption of the old refrigerator is 234~joules per second, and the power consumption of the new refrigerator is 126~joules per second, so the power consumption of the new refrigerator is $234-126=108$~joules per second less than the power consumption of the old refrigerator. At a rate of 108~joules per second, the total difference in the energy used in one \emph {minute} is $60(108)=\num {6480}$~joules. Choice~\TextChoice {2} is correct.
let diagram = Power of Old and New Appliances \par \medskip \par \begin {tabular}{|l|z{4}|z{4}|} \cline {2-3} \multicolumn {1}{c|}{} & \multicolumn {2}{c|}{Power (joules per second)} \\ \hline \multicolumn {1}{|c|}{Appliance} & \multicolumn {1}{>{\centering \arraybackslash }p{4.5em}|}{Old} & \multicolumn {1}{>{\centering \arraybackslash }p{4.5em}|}{New} \\ \hline Refrigerator & 234 & 126 \\ \hline Microwave & 1640 & 1023 \\ \hline Air conditioner & 6200 & 2800 \\ \hline Television & 142 & 67 \\ \hline \end {tabular}
let choicesAlign = null
let calculator = True
let multipleQuestion = information
let diagramPostText = A household replaced old appliances with new models to conserve energy. The table above shows the power consumption of a household’s old and new appliances. The power, in joules per second, is the energy used, in joules, each second the appliance is active.
let diagramPreText = null
let percent_correct = null