let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 8
let problemSetNumber = 4
let test = SAT
let subject = Mathematics
let category = Problem Solving and Data Analysis/One-variable data: distributions and measures of center and spread
let difficulty = 3
let question = The average (arithmetic mean) power consumption of the four new appliances, in joules per second, is how much less than average power consumption of the four old appliances?
let choices = 432,850,1050,4200
let answer = C
let solution = First, we compute the average power consumptions for the old and new appliances: \par \begin {align*} \text {old average} &= \frac {234+\num {1640}+\num {6200}+142}{4} = \Si {2054}{joules per second} \\[2ex] \text {new average} &= \frac {126+\num {1023}+\num {2800}+67}{4} = \Si {1004}{joules per second} \\ \end {align*} \par Thus, the average power consumption of the new appliances is $\num {2054}-\num {1004}=\num {1050}$~joules per second less than the average power consumption of the old appliances.
let diagram = null
let choicesAlign = null
let calculator = True
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null