let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 1
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 2
let question = According to the passage, Kungawo counts the goats when Bokamoso takes them to the kraal because
let choices = ['he knows that predators sometimes roam the plain.', 'he has already agreed to sell the goats.', 'he doubts Bokamoso is always sufficiently watchful.', 'the goats are unruly and frequently wander off.']
let answer = C
let solution = In \reflines {HeMayMilkTree}, the passage states, “He may have suspected that she sometimes fell asleep against the milk-tree.” In short, Kungawo suspects that Bokamoso may not always be as attentive or watchful as she should be, and choice~\TextChoice {3} is correct. The passage offers no support for any of the other answer choices.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null