let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 10
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 2
let question = As used in \reflines {charge}, “charge” most nearly means
let choices = ['care.', 'instruction.', 'command.', 'price.']
let answer = A
let solution = The context in which “charge” appears is “Bokamoso knew it was time to gather her goats and herd them back to the kraal, where Kungawo would count them, just as he did every evening, to make sure that Bokamoso had been suitably diligent in caring for the goats in her charge” (\reflines {BokamosoCharge}). The “charges” are the goats, which are her care. In this sense, “charge” fits with the definition “Care; custody: \emph {a child put in my charge}” (\emph {The American Heritage Dictionary of the English Language, Fifth Edition}). Choice~\TextChoice {1} is correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null