let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 11
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 4
let question = Which choice best supports the claim in the first sentence of the passage?
let choices = ['\\reflines [Capital]{ThisIncreaseThing} (“This increase \\Ellipsis thing”)', '\\reflines [Capital]{SadlyAchievement} (“Sadly \\Ellipsis achievement”)', '\\reflines [Capital]{ToRichardSimple} (“To \\Ellipsis simple”)', '\\reflines [Capital]{ItTurnsUniversities} (“It turns \\Ellipsis universities”)']
let answer = D
let solution = Choice~\TextChoice {4} is correct. The first sentence of the passage states, “In high schools, colleges, and universities across the country, grades are rising.” Note that this sentence identifies three types of schools, so we need an answer choice that supports the claim that grades have been rising in all three types. “It turns out that at the same time high-school GPA’s have been rising, similar increases have occurred at four-year colleges and universities” makes just that claim. \par Choice~\TextChoice {1} is wrong because it assumes the increase based on the first sentence but does not offer any evidence (or even a claim) that the increase is occurring. \par Choice~\TextChoice {2} is wrong because it offers no support for the claim other than its tacit acceptance that there is an increase. \par Choice~\TextChoice {3} is wrong. It states only that an explanation is simple (to one person), not what the explanation actually explains.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null