let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 12
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing text structure/Analyzing part-whole relationships
let difficulty = 3
let question = The explanation mentioned in \reflines {ItCouldThings} (“It could \Ellipsis things”) is presented in order to
let choices = ['rebut a common bias about the abilities of members of younger generations.', 'present a possible reason that the author believes is not actually correct.', 'highlight an important point for understanding a study’s methodology.', 'offer a larger context for the political motivations of those who conducted a study.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The question is why grades of high-school students are rising. There are, the author suggests, essentially two explanations. The first is that grades are rising just because today’s students are smarter than yesteryear’s. The second is that grades are rising for reasons that are less directly related to achievement. The sentence cited in this question, “It could tell us that the future is in good hands, that the current generation of young people comprises vast numbers of bright, motivated students in whose hands the nation will be safe when they come of age to run things,” is the first possible explanation (\IE , that rising grades are related to rising achievement or ability). But the author does not believe this conclusion is likely. In \reflines {SadlyAchievement}, the author says, “Sadly, it \emph {is} almost certainly something else: grade inflation, a phenomenon in which grades rise for reasons unrelated to achievement” (emphasis in original). \par Choice~\TextChoice {1} is wrong. Although it does seem likely that the author had in mind a bias common among many generations about the abilities and motivations of younger generations, the fact that the author does not accept the explanation that the question refers to undermines choice~\TextChoice {1} and makes it incorrect. \par Choice~\TextChoice {3} is wrong. The possibility that students are getting smarter is not directly related to the methodology of the College Board study. The methodology is not explicitly mentioned, but we can infer that essentially the College Board collected lots of data and compiled average grades for different years. There certainly are important considerations for the methodology. For example, did the College Board use self-reported data, which is subject to distortion if students lie? Did the study allow students to opt out of reporting their grades? But the possibility that students are just bright and motivated does not relate to these questions. \par Choice~\TextChoice {4} is wrong. If we accept the author’s premise that there are basically two possible reasons for the increase in grades, then mentioning one of them does not explain, clarify, reveal, expose, or do anything else for the study authors’ political motivations. In short, the author is simply presenting two possible reasons. \par Note that later in the passage, in \reflines {AgainImproved}, the author admits a third possibility, the improvement of teachers. But that admission does not affect the basic thrust of the points above.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null