let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 13
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Using analogical reasoning
let difficulty = 3
let question = Based on the views expressed in the passage, which high school is most likely to have had GPA’s rise as a result of grade inflation?
let choices = ['A public school in a rural area where students tend to work on farms after graduating', 'A public school located in a large city where there are many manufacturing plants', 'A private school hoping to attract students because of prestigious colleges alumni have attended', 'A public school located in an urban area noted for its diverse immigrant population']
let answer = C
let solution = Choice~\TextChoice {1} is wrong because nothing in the passage supports the idea that there is grade inflation in rural schools. The passage discusses both suburban and urban public schools, private schools, and religious schools. Schools in rural America are not mentioned or alluded to. Moreover, the notion that students at this hypothetical school tend to go into work immediately after high school eliminates the concern cited in the passage about college placement. See, \EG , \reflines {PrivateAdmittedTo} and \reflines {AsForInflation}. \par Choices \TextChoice {2} and~\TextChoice {4} are wrong because urban schools have seen little or no grade inflation. \par Choice~\TextChoice {3} is correct. In \reflines {PrivateAdmittedTo}, the passage states, “Private schools need to attract future students, and the best way to do so is to be able to show parents the list of elite colleges and universities that previous students were admitted to.” Choice~\TextChoice {3} deals with just such a situation.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null