let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 14
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 4
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{InReligiousIdentical} (“In religious \\Ellipsis identical”)', '\\reflines [Capital]{ButDuringFalling} (“But during \\Ellipsis falling”)', '\\reflines [Capital]{MichaelAnotherProblem} (“Michael \\Ellipsis another problem”)', '\\reflines [Capital]{PrivateAdmittedTo} (“Private \\Ellipsis admitted to”)']
let answer = D
let solution = Choice~\TextChoice {4} is correct. It cites the sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null