let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 15
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 3
let question = As used in \reflines {frozen}, “frozen” most nearly means
let choices = ['fixed.', 'numb.', 'chilled.', 'preserved.']
let answer = A
let solution = The full context for “frozen” is “To be more specific, the study finds that grades in private high schools and in suburban public schools are rising significantly while grades in urban public schools are essentially frozen” (\reflines {ToBeFrozen}). The use of “while” in the sentence establishes a contrast. Grades in private high schools and in suburban public schools are rising; those in urban public schools are not. “Frozen” must thus indicate either a lack of movement of grades or a movement down. The passage makes it clear that there has been little movement: “students’ average GPA in urban public schools rose only from 3.26 to~3.28” (\reflines {Students328}). Thus, “frozen” must refer to a lack of change, and choice~\TextChoice {1} is correct. Note that \emph {The American Heritage Dictionary of the English Language} offers the following as one of the definitions of “freeze”: “Kept at a fixed level: \emph {frozen rents}.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null