let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 16
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing word choice
let difficulty = 5
let question = What main effect do the phrase “marketing scheme” (\reflines {MarketingScheme}) and the word “appeasement” (\reflines {Appeasement}) have on the tone of the passage?
let choices = ['They contribute to a sympathetic tone that indicates the author’s awareness of the difficulties school administrators face.', 'They contribute to a subtle condemnation of schools’ use of grades in manners that are not directly related to student achievement.', 'They contribute to an overtly mocking tone that indicates the author does not accept the findings of certain researchers.', 'They contribute to a concerned but hopeful tone regarding the future employment prospects for current students.']
let answer = B
let solution = Choice~\TextChoice {1} is incorrect. Though it is possible to infer from the two situations described that school administrators face difficulties, the phrase “marketing scheme” and the word “appeasement” do not suggest any level of sympathy. Both “scheme” and “appeasement” have negative connotations in the context in which they appear. \par Choice~\TextChoice {2} is correct. Both “scheme” and “appeasement” have negative connotations in the context in which they appear, in particular in the reference to “the easiest route of appeasement” (\reflines {TheEasiestAppeasement}). The author refers to the difference in the rates at which grades are rising as “troubling” (\reflines {troubling}), so we can infer that the author certainly does not approve of the situation. In if administrators are raising grades as part of a “scheme” or an effort at “appeasement,” it stands to reason that the author has chosen these words as a subtle means of condemnation. \par Choice~\TextChoice {3} is incorrect. The use of “marketing scheme” and of “appeasement” is not related to any criticism of the sources the author cites. It would be possible for the author to use these terms to condemn the sources (in particular, Richard Weissbourd, \reflines {RichardWeissbourd}, who is the person cited most recently). But there would have to be a clear indication of sarcasm, and the sentence “The concern here is understandable” (\reflines {TheConcernUnderstandable}) removes the possibility of sarcasm. \par Choice~\TextChoice {4} is incorrect. The author is not referring to “future employment prospects” here (or, in fact, anywhere in the passage).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null