let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 17
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining implicit meanings
let difficulty = 3
let question = The author uses the “larger context” referred to in \reflines {LargerContext} primarily to suggest that
let choices = ['both public and private high schools are motivated by the same concerns.', 'current students outperform those of the past in even non-academic respects.', 'a phenomenon considered recent has actually been occurring for decades.', 'the focus of Hurwitz and Weissbourd on high schools overlooks important information.']
let answer = D
let solution = The author refers to the “larger context” more than once. In \reflines {TheCollegeContext}, for example, the author states, “The College Board’s study, though, needs to be put into a larger context.” Later, after explaining that grades are rising also at four-year colleges and universities, the author states, “In short, what we are seeing in high schools is also occurring at colleges and universities—but not at urban public high schools. Why they are the lone exception is an important question to answer” (\reflines {InShortAnswer}). The point is not explicit, but it is strongly implied: grade inflation in high schools is only part of the issue, and we need to look at the entire issue. Since Hurwitz and Weissbourd focus only on high schools and since the author of the passage believes that colleges and universities should also be considered, choice~\TextChoice {4} is correct. \par Choice~\TextChoice {1} is incorrect because the “larger context” is the rise of grades in colleges and universities and would have little to do with establishing that two different kinds of high schools are motivated by similar factors. \par Choice~\TextChoice {2} is incorrect because the passage does not discuss non-academic performance. \par Choice~\TextChoice {3} is incorrect, though some students might be drawn to it. Let’s begin with the appeal of this answer choice. In \reflines {TheTrendGradesInternal}, the author states, “The trend [the increase in college grades], moreover, is longstanding. In the~1940s, the most common grade at American colleges and universities was a~C (roughly 35~percent of all grades).” It certainly \emph {seems} as if the author is stating that “a phenomenon considered recent has actually been occurring for decades.” However, this answer choice is incorrect for a few reasons. First, note that the question asks for the \emph {primary} reason the author refers to the “larger context.” If we argue that choice~\TextChoice {3} is correct, we are essentially arguing that the author brought up the larger context of grade inflation in colleges and universities to make a point about longstanding grade inflation—even though the smaller context is about grade inflation in high schools and the larger context does not suggest that grades have been rising in high school for decades. Moreover, the author’s primary point in raising the issue of grade inflation in colleges and universities is to make the point that grade inflation is not restricted to high schools. In other words, the author’s point in raising the larger context is not about looking at a broader time frame but about looking at more institutions.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null