let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 18
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing purpose
let difficulty = 2
let question = The main reason that the author includes the information about Haverford College in \reflines {HaverfordCollege} is to
let choices = ['reveal an exception to a disturbing trend.', 'offer a solution to a problem discussed earlier.', 'highlight the difference between public and private schools.', 'cite a specific instance of a widespread practice.']
let answer = D
let solution = Choice~\TextChoice {4} is correct. In the preceding sentence, the author states, “It turns out that at the same time high-school GPA’s have been rising, similar increases have occurred at four-year colleges and universities” (\reflines {ItTurnsUniversities}). The sentence in \reflines {HaverfordCollege} begins with “For example.” Clearly, Haverford is intended to be a single example (with concrete numbers) to demonstrate the increase in GPA’s in colleges—in other words, “a specific instance of a widespread practice.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null