let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 19
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 3
let question = According to the figure, the mean GPA in US public four-year colleges and universities in~2008 was closest to the mean GPA in
let choices = ['private colleges and universities in~1983.', 'private colleges and universities in~1988.', 'public colleges and universities in~1983.', 'public colleges and universities in~1988.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. A horizontal line drawn through the point corresponding the mean GPA in public schools in~2008 comes closest to the point corresponding to the mean GPA for private schools in~1988. Both are slightly higher than~3.0.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null