let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 2
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 1
let question = In the passage, the plain is compared to a
let choices = ['food.', 'friend.', 'wilderness.', 'protector.']
let answer = A
let solution = In \reflines {ButOven}, the passage sates, “But the arid plain, treeless except near the river, testified to a long history of the sun’s torment, like vetkoek bread left too long in the oven.” Choice~\TextChoice {1} is thus correct. The passage offers no support for any of the other answer choices.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null