let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 20
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 3
let question = Which statement from the passage is most directly supported by the data in the figure?
let choices = ['\\reflines [Capital]{AndAsCause} (“And as \\Ellipsis cause”)', '\\reflines [Capital]{HaverfordCollege} (“For example \\Ellipsis 2007”)', '\\reflines [Capital]{OverallUniversities} (“Overall \\Ellipsis universities”)', '\\reflines [Capital]{TodayGrades} (“Today \\Ellipsis grades”)']
let answer = C
let solution = Choice~\TextChoice {1} is incorrect. For one thing, at this point, the passage is still discussing mainly high-school grade inflation. For another, the graph does not suggest anything about symptom versus cause. \par Choice~\TextChoice {2} is wrong because the graph is about mean GPA’s from a variety of schools and does not allow inferences about any particular school. \par Choice~\TextChoice {3} is correct. The graph shows the mean GPA’s for public and private schools from 1983 to~2013, and for both types of schools, the increases are similar. \par Choice~\TextChoice {4} is incorrect. The graph shows that GPA’s rose, but it does not give data sufficient for us to determine the percentage of grades that were~A’s. There’s also the small point that the graph ends with data for~2013, and the sentence in the passage begins with “Today.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null