let tableName = TB12
let formCode = TB-12
let passageCode = pm-34
let questionNumber = 21
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 2
let question = Information in the figure is most useful for addressing which question provoked by the passage?
let choices = ['Was grade inflation limited to high schools during the period the College Board studied?', 'Is it likely that grade inflation will continue at high schools, colleges, or universities?', 'Did increases in GPA’s in colleges and universities exceed increases in GPA’s in high schools during the same period?', 'What is the primary reason that grades increased in colleges and universities from 1983 to~2013?']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The graph clearly shows an increase in grades in colleges and universities during the time period discussed for high schools. While the graph does not give proof of grade inflation during this time, the data are strongly suggestive of grade inflation, meaning that the graph does help address the question in this answer choice. As for the question itself, it is strongly suggested by the sentence “What happens if we look for evidence of grade inflation elsewhere?” in \reflines {WhatElsewhere} of the passage.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null