let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 22
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 3
let question = According to the passage, \emph {M.~thermoacetica}‑CdS differs from natural photosynthetic processes in which significant way?
let choices = ['\\emph {M.~thermoacetica}‑CdS extracts a greater quantity of~\\ce {CO2} from the environment.', '\\emph {M.~thermoacetica}‑CdS is more efficient at converting the Sun’s energy to a usable form.', '\\emph {M.~thermoacetica}‑CdS can immediately be put into use for commercial purposes.', '\\emph {M.~thermoacetica}‑CdS is more widespread in the natural world.']
let answer = B
let solution = Choice~\TextChoice {1} is incorrect. The passage does not state the amount of~\ce {CO2} any processes extract from the environment, so we cannot conclude that \emph {M.~thermoacetica}‑CdS or photosynthetic processes extract any \ce {CO2} or, if so, which extracts more. \par Choice~\TextChoice {2} is correct. In \reflines {MoreoverPhotosynthesis}, the passage states, “Moreover, \emph {M.~thermoacetica}‑CdS, as the enhanced bacteria is now known, is approximately 80~percent efficient, far more efficient than chlorophyll, the natural agent at work in photosynthesis.” \par Choice~\TextChoice {3} is incorrect. In fact, the passage contradicts the claim in this answer choice. In \reflines {ThoughApplications}, the passage states, “Though \emph {M.~thermoacetica}‑CdS is not ready for prime time yet, Sakimoto sees the potential for widespread commercial applications.” Later, in \reflines {AtPresentGoes}, the point is repeated: “At present, it does not appear that \emph {M.~thermoacetica}‑CdS is likely to replace traditional solar panels, but the bacterium is not yet in even its embryonic stage as far as human use goes.” \par Choice~\TextChoice {4} is incorrect. The passage does not state that \emph {M.~thermoacetica}‑CdS is “more widespread” in the natural world. In fact, it may not exist in the natural world.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null