let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 23
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 5
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{SolarProvides} (“Solar \\Ellipsis provides”)', '\\reflines [Capital]{SakimotoBeganDemands} (“Sakimoto \\Ellipsis demands”)', '\\reflines [Capital]{ByIntroducingAbsorber} (“By introducing \\Ellipsis absorber”)', '\\reflines [Capital]{MoreoverPhotosynthesis} (“Moreover \\Ellipsis photosynthesis”)']
let answer = D
let solution = Choice~\TextChoice {4} is correct. It cites the sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null