let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 24
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 1
let question = According to the passage, one of the reasons that coal supplies more electricity than solar is that
let choices = ['there are many already constructed facilities to extract coal and transform it into energy.', 'the coal industry has powerful political allies to ensure coal’s continued use.', 'coal is found all across the nation, making it easy to obtain locally.', 'most contemporary electrical appliances are able to run on coal but not solar power.']
let answer = A
let solution = Choice~\TextChoice {1} is correct. In \reflines {ThereArePlants}, the passage states, “There are several reasons [why we get more electricity from coal than from solar power], including existing infrastructure (that is, the number of coal mines and processing plants)~\Ellipsis ~.” This quotation is almost perfectly paraphrased in choice~\TextChoice {1}. \par Choice~\TextChoice {2} is incorrect. The passage makes no mention of politics. \par Choice~\TextChoice {3} is incorrect. The passage does not state that coal is found “all across the nation.” \par Choice~\TextChoice {4} is incorrect. In fact, it’s absurd. How electricity is generated has essentially nothing to do with which appliances can use it.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null