let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 25
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 2
let question = As used in \reflines {suited}, “suited” most nearly means
let choices = ['pleased.', 'attired.', 'housed.', 'adapted.']
let answer = D
let solution = Choice~\TextChoice {4} is correct. The full context for “suited” is “The Sun-baked states of Florida, Texas, and Arizona, for example, are better suited than, say, Maine, Minnesota, and Alaska to benefit from solar power” (\reflines {TheSunPower}). One of the meanings of “suit” is “To make appropriate or suitable; adapt: \emph {builders who suit the house to the owner’s specifications}” (\emph {The American Heritage Dictionary of the English Language, Fifth Edition}). “Adapted” is thus the best of the four options.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null