let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 26
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Using analogical reasoning
let difficulty = 2
let question = Based on the passage, Sakimoto’s hopes for widespread use of \emph {M.~thermoacetica}‑CdS would be most undermined by a study that
let choices = ['proved that current use of fossil fuels is creating an abundance of~\\ce {CO2} in the Earth’s atmosphere.', 'revealed that the size of the containers necessary for \\emph {M.~thermoacetica}‑CdS would exceed available space in most areas.', 'surveyed Americans and found that most people are unaware of the fuel sources used to generate the electricity they use at home.', 'established that the current supply of accessible coal is projected to be sufficient to meet US energy demands for about 110~years.']
let answer = B
let solution = Choice~\TextChoice {1} is incorrect. If anything, the abundance of~\ce {CO2} is a plus for Sakimoto’s hopes. \emph {M.~thermoacetica}‑CdS converts \ce {CO2} into energy, so more \ce {CO2} cannot diminish his hopes. \par Choice~\TextChoice {2} is correct. In \reflines {OurSays}, the passage quotes Sakimoto: “‘Our algal biofuels are much more attractive, as the whole \ce {CO2}-to-chemical apparatus is self-contained and only requires a big vat out in the sun,’ he says.” However, if the size of the vats were too great for available space in most areas, then even this apparently modest requirement would be an obstacle to widespread use of \emph {M.~thermoacetica}‑CdS. \par Choice~\TextChoice {3} is incorrect. Whether Americans know where their electricity comes from is not directly relevant to Sakimoto’s hopes. We might stretch things too far by assuming that (1)~Americans do not know where their electricity comes from, (2)~they therefore are not likely to understand the importance of replacing coal and other non-renewable sources as the primary sources of electricity, (3)~the collective political will to use non-polluting sources will thus not exist, and (4)~Sakimoto’s hopes will not be realized. But this string of inferences becomes weaker with each link and truly involves going beyond anything included in the passage. Indeed, the entire string can be weakened by a simple process of education Americans about the consequences of their use of electricity. \par Choice~\TextChoice {4} is incorrect. The figure cited (110~years) appears to be accurate, but the idea that coal will run out in about a century is hardly an obstacle to a replacement. In fact, the figure in this answer choice argues strongly in favor of finding replacement sources of energy.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null