let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 27
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 3
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{SolarEnergyCoal} (“Solar \\Ellipsis coal”)', '\\reflines [Capital]{PhotosynthesisInefficient} (“Photosynthesis \\Ellipsis inefficient”)', '\\reflines [Capital]{OurSays} (“Our \\Ellipsis says”)', '\\reflines [Capital]{HoweverUse} (“However \\Ellipsis use”)']
let answer = C
let solution = Choice~\TextChoice {3} is correct. It cites the sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null