let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 28
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 3
let question = As used in \reflines {meeting}, “meeting” most nearly means
let choices = ['satisfying.', 'encountering.', 'undergoing.', 'paying.']
let answer = A
let solution = The full context in which “meeting” occurs is “Sakimoto began with \emph {Moorella thermoacetica}, a nonphotosynthetic bacterium that naturally transforms carbon dioxide~(\ce {CO2}) into acetic acid, an especially useful chemical for meeting energy demands” (\reflines {SakimotoBeganDemands}). In this context, one of meeting demands, “meeting” means being sufficient for, fulfilling, or satisfying (all definitions provided by \emph {The American Heritage Dictionary of the English Language, Fifth Edition} along with the example phrase “meet all the conditions in the contract”). Choice~\TextChoice {1} is thus correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null