let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 29
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing text structure/Analyzing part-whole relationships
let difficulty = 3
let question = The last sentence of the passage serves mainly to
let choices = ['underscore the limitations of a development.', 'indicate future avenues of exploration.', 'demonstrate the short-term benefits of a discovery.', 'resolve a conflict highlighted in research studies.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The final sentence (\reflines {HoweverUse}) reads, “However, Sakimoto is excited about the possibilities, which include replacing the non-green process by which solar cells are currently created and searching for a naturally occurring version of \emph {M.~thermoacetica}‑CdS—while at the same time tweaking his creation to make it more suitable for industrial use.” In particular, it refers to three things: (1)~changing a current process, (2)~looking at nature for something similar to \emph {M.~thermoacetica}‑CdS, and (3)~modifying the current version of \emph {M.~thermoacetica}‑CdS. All three of these are “future avenues of exploration.” \par Choice~\TextChoice {1} is incorrect. The point of the sentence is not to emphasize limitations. If this were the point, it would make little sense to state that “Sakimoto is excited about the possibilities” (\reflines {SakimotoPossibilities}). \par Choice~\TextChoice {3} is incorrect. Nothing in the sentence indicates “short-term benefits.” \par Choice~\TextChoice {4} is incorrect. The passage does not note any “conflict” that needs to be resolved.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null