let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 3
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 3
let question = As used in \reflines {divide}, “divide” most nearly means
let choices = ['branch.', 'rupture.', 'line.', 'breach.']
let answer = C
let solution = The full context for “divide” is “Where was the divide? she wondered. Somewhere between the milk-plant and the city, there must be a spot separating tradition from modern convenience, the past from the future” (\reflines {WhereFuture}). In this context, it is clear that the “divide” corresponds to “a spot separating” things. Choice~\TextChoice {3} is the best answer for this context.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null