let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 30
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 1
let question = According to the table, in~2015, which fuel source had the highest amount produced as a percent of maximum capacity?
let choices = ['Natural gas', 'Coal', 'Nuclear', 'Geothermal']
let answer = C
let solution = According to the table, the percentages for natural gas, coal, nuclear, and geothermal in~2015 were 35, 55, 92, and~73. Choice~\TextChoice {3} is thus correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null