let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 31
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 2
let question = Which statement about US electrical production in~2015 is supported by data represented in the table?
let choices = ['Energy from wind made up a greater percentage of US electrical consumption than did energy from hydro and biomass combined.', 'The summer capacity for petroleum was less than the summer capacity for wind.', 'Some renewable energy sources produced more kilowatt hours of energy than coal did.', 'No other energy source had a lower summer capacity than solar power did.']
let answer = B
let solution = Choice~\TextChoice {1} is wrong. The percentage for wind was~4.60. The percentage for hydro was~6.01. There is no need to perform a calculation here; all by itself, hydro made up a greater percentage of US usage than wind. \par Choice~\TextChoice {2} is correct. According to the table, the summer capacity for petroleum was 36.8~gigawatts. The summer capacity for wind was 72.6~gigawatts. \par Choice~\TextChoice {3} is incorrect. To begin with, the table does not indicate which energy sources are renewable, so we hard hard pressed to identify those sources without outside knowledge or information from the passage (which itself provides little guidance). But if we assume that all sources other than coal are renewable (an obviously absurd assumption), choice~\TextChoice {3} is still wrong. Coal produced \num {1352.3}~kilowatt hours of energy per year. No other energy source in the table produced more. \par It is possible that some students may object that it is possible that there was a renewable energy source that was not included in the passage and that it could have produced more energy than coal. To this objection, there are two responses. The first is that the question asks for a conclusion supported by the data in the table. The hypothetical energy source is not included in the table. The second is that there is no such energy source anyway. The sum of the numbers in the first column is~98.17, meaning that the list of energy sources includes all but slightly less than 2~percent of all US electrical production. For a hypothetical source to produce more than coal, it would have to produce more than 32.63~percent of the US production. The chart does not allow for such a number. \par To be clear, the point here is not that students should add up the table. The point is that even if there were another energy source, the table doesn’t include it—and there isn’t one anyway. \par Choice~\TextChoice {4} is incorrect. The summer capacity for solar power was 13.66~gigawatts. The summer capacity for geothermal was 2.54~gigawatts.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null