let tableName = TB12
let formCode = TB-12
let passageCode = 
let questionNumber = 32
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing quantitative information
let difficulty = 4
let question = If Sakimoto’s goal for electricity from \emph {M.~thermoacetica}‑CdS solar power is to be realized, which number in the table most needs to be larger in tables of electrical production for future years?
let choices = ['Annual energy for nuclear power', 'Summer capacity for coal', 'Amount produced as percent of maximum capacity for natural gas', 'Percent of US consumption for solar']
let answer = D
let solution = Sakimoto’s goal is identified in \reflines {HisGas}: “his goal is that this source will one day produce more electricity than coal and natural gas.” There are essentially two ways this result can come to pass. The first occurs if both coal and natural gas produce smaller percentages of US production. In such a case, it is at least within the realm of theoretical possibility that solar power could make up a bigger percentage than coal and natural gas. The other occurs if solar power fills a bigger portion of US production, and it is this possibility that is contemplated in choice~\TextChoice {4}, which is the correct answer.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null