let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 33
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 4
let question = In Passage~1, Webster states that South Carolina is unwilling to
let choices = ['respect the will of the majority of its own citizens.', 'participate in Senate debates about proposed new legislation.', 'name explicitly the laws that it considers unconstitutional.', 'rely on courts to determine the constitutionality of laws.']
let answer = D
let solution = Choice~\TextChoice {4} is correct. In \reflines {TheyJustice}, Webster states, “they cannot consent to try their accuracy by the courts of justice.” A reasonable paragraphs is “South Carolina is unwilling to submit its judgment about the unconstitutionality of laws to the courts.” \par The other three answer choices do not find support in Webster’s words (or, for that matter, in Hayne’s).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null