let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 34
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing word choice
let difficulty = 3
let question = The figurative language in \reflines {ARopeOfSand} (“a rope of sand”) serves mainly to suggest
let choices = ['adaptability.', 'flexibility.', 'flimsiness.', 'permanence.']
let answer = C
let solution = Choice~\TextChoice {3} is correct. The “rope of sand” (\reflines {RopeOfSand}) occurs when there is “no power” (\reflines {NoPower}) other than the states to decide “such questions” (\reflines {SuchQuestions}, constitutional questions). Webster’s implication is that the bond connection the states to each other and to the federal government is weak, impermanent, and easily broken—in short, flimsy.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null