let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 35
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining implicit meanings
let difficulty = 3
let question = In Passage~2, Hayne indicates that what Webster calls “a ridiculous notion” (\reflines {ARidiculousNotion}) is
let choices = ['one of the founding principles of the country.', 'a common practice in other nations.', 'an idea Webster himself once endorsed.', 'a deliberate distortion of Hayne’s actual position.']
let answer = C
let solution = Choice~\TextChoice {3} is correct. In \reflines {SouthOpposition}, Haynes argues, “South Carolina has not gone one step further than [Thomas Jefferson] himself was disposed to go, in relation to the very subject of our present complaints; not a step further than the statesmen from New England were disposed to go under similar circumstances; \emph {no further than the senator from Massachusetts himself once considered as within ‘the limits of a constitutional opposition’}” (emphasis added; brackets in original). \par No other answer choice finds support in Passage~2.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null