let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 36
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 3
let question = As used in \reflines {open1}, \reflines {open2}, and \reflines {open3}, “open” most nearly means
let choices = ['not hidden.', 'not covered.', 'accessible.', 'susceptible.']
let answer = A
let solution = Choice~\TextChoice {1} is correct. When Webster talks about “open resistance” (in all three instances the question refers to), he means that the states will freely and visibly disobey federal laws. In this sense, the usage is consistent with the following definition of “open”: “Carried on in full view of others; not hidden or private: \emph {open warfare; open family strife}” (\emph {The American Heritage Dictionary of the English Language, Fifth Edition}).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null