let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 37
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing point of view
let difficulty = 5
let question = Based on Passage~2, which statement best reflects Hayne’s view of letting the federal government alone have the power to determine whether laws are constitutional?
let choices = ['Such a power deprives the states of their autonomy.', 'The federal government has abused this power too often.', 'Allowing the states to share this power would divide the nation.', 'The federal government takes too long to make such determinations.']
let answer = A
let solution = Hayne states, “[a]s to the doctrine that the federal government is the exclusive judge of the extent, as well as the limitations of its powers, it seems to me to be utterly subversive of the sovereignty and independence of the states” (\reflines {AsToStates}). In other words, allowing the federal government to determine whether its own laws are constitutional undermines states’ autonomy. Choice~\TextChoice {1} is correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null