let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 38
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 4
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{TheSenatorConstitution} (“The senator \\Ellipsis constitution”)', '\\reflines [Capital]{SheHasInterests} (“she has \\Ellipsis interests”)', '\\reflines [Capital]{AsToStates} (“as to \\Ellipsis states”)', '\\reflines [Capital]{ItMakesPower} (“It makes \\Ellipsis power”)']
let answer = C
let solution = Choice~\TextChoice {3} is correct. It cites the words relied upon by the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null