let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 39
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing multiple texts
let difficulty = 3
let question = Which statement best describes the relationship between the views expressed in the two passages?
let choices = ['Hayne disagreed with the fundamental claim advanced by Webster.', 'Webster introduced a consideration that Hayne admitted he had not considered.', 'Webster and Hayne both disagreed with the argument made by South Carolina.', 'Neither Webster nor Hayne challenged the power of the federal government.']
let answer = A
let solution = Choice~\TextChoice {1} is correct. Webster’s argument is that allowing states to determine whether federal laws are unconstitutional would weaken the bonds of the nation and allow states to separate themselves from the views of other states, from the Constitution, and from the federal government. Hayne’s argument is that allowing the federal government to determine the constitutionality of its own laws will give the it too much power and weaken the power of the states excessively. In short, Hayne disagrees completely with Webster’s primary point. \par Choice~\TextChoice {2} is incorrect because nothing in either passage supports it. \par Choice~\TextChoice {3} is incorrect because Hayne, as a senator from South Carolina, is representing his state’s position. \par Choice~\TextChoice {4} is incorrect because Hayne clearly challenges the power of the federal government by arguing that states themselves can determine the constitutionality of federal laws.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null