let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 4
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing text structure/Analyzing part-whole relationships
let difficulty = 4
let question = The size of the portions of stew serves to
let choices = ['convey the poverty Bokamoso lives in.', 'indicate that an arrival was unforeseen.', 'highlight the value of dietary protein.', 'suggest the lateness of the hour.']
let answer = B
let solution = Choice~\TextChoice {2} is incorrect. In \reflines {ApparentlyVisitors}, the passage states, “Apparently, Kungawo had not been expecting the visitors.” The very next sentence says, “The portions of stew were half what they normally were” (\reflines {ThePortionsWere}). The juxtaposition of these sentences allows us to infer a causal relationship. In this case, it makes sense to infer that the portions were small because Kungawo was sharing the stew. Had he expected visitors, he presumably would have made more stew. \par Choice~\TextChoice {1} is incorrect because the passage does not suggest that Bokamoso and her grandfather live in poverty. Even if we accept that their life is one of poverty, the portions of stew do not convey that when there is a much simpler explanation—that Kungawo has been taken by surprise and is unprepared for the visitors. \par Choice~\TextChoice {3} is incorrect. The issue of protein is certainly in the passage, but the size of the portions of stew is unrelated to the issue of protein. \par Choice~\TextChoice {4} is wrong because the size of the portions of stew is not related to the hour. The passage seems to suggest that stew is customary when Bokamoso returns home from her job tending the goats, and the size of the portions is related more to the visitors than to any lateness.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null