let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 40
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing multiple texts
let difficulty = 1
let question = Which statement best expresses Webster’s and Hayne’s respective views of unconstitutional laws?
let choices = ['Webster believed that they were unfortunately common, while Hayne considered them rare.', 'Webster considered the federal government as the only power to overturn them, while Hayne believed states should also have that right.', 'Webster claimed amending the Constitution was the only remedy for them, while Hayne stated only courts could overturn such laws.', 'Webster expressed confidence that the legislative process would prevent them, while Hayne believed them inevitable.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The fundamental dispute in the two passages is about whether states should have the power to declare federal laws unconstitutional. \par Choice~\TextChoice {1} is incorrect. Webster does not express a view about the frequency of unconstitutional laws. Hayne refers to laws that South Carolina considered unconstitutional, and it is thus unreasonable to infer from that fact that Hayne believes such laws “rare.” \par Choice~\TextChoice {3} is wrong. Webster does not refer to amendments, and Hayne does not state that courts are the sole arbiters. \par Choice~\TextChoice {4} is wrong. Webster does not suggest that the legislative process is likely to prevent unconstitutional laws.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null