let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 41
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Synthesis/Analyzing multiple texts
let difficulty = 3
let question = Webster would most likely have responded to Hayne’s claim about the right of states to determine the constitutionality of federal laws by claiming it
let choices = ['was tried and subsequently rejected.', 'would elevate states above federal law.', 'was explicitly prohibited by the Constitution.', 'should be exercised only in extreme cases.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. In \reflines {TheLibertyConstitution}, Webster says that such a power would give states “the liberty of placing their own opinions above the judgment of all others, above the laws, and above the Constitution.” While “all others” in this context includes states, it does not exclude the federal government, and certainly the Constitution is an aspect of federal law. \par The other answer choices are all incorrect because Webster does not say anything to support them.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null