let tableName = TB12
let formCode = TB-12
let passageCode = pd-37
let questionNumber = 42
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 4
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{WhatIsFeeling} (“What is \\Ellipsis feeling”)', '\\reflines [Capital]{FourAndTwentyUnion} (“Four-and-twenty \\Ellipsis union”)', '\\reflines [Capital]{TheLibertyThey} (“the liberty \\Ellipsis they”)', '\\reflines [Capital]{TheLibertyConstitution} (“the liberty \\Ellipsis Constitution”)']
let answer = D
let solution = Choice~\TextChoice {4} is correct. It cites the phrase relied on in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null