let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 43
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Determining central ideas and themes
let difficulty = 3
let question = The passage is primarily concerned with
let choices = ['examining the methodologies of two studies and highlighting the flaws in one.', 'explaining why two apparently contradictory studies are actually in complete agreement.', 'identifying a longstanding scientific debate and arguing in favor of a single conclusion.', 'explaining the results of a study that calls into question an earlier study.']
let answer = D
let solution = As a whole, the passage discusses two studies (Milliken’s and Day’s) but does devote more time to Day’s. The conclusions of the studies are contradictory, but the passage does not explicitly take sides. It is possible to infer that the author considers Day’s study to be the more reliable given the structure of the study, but it is also possible to infer that the author is simply reporting more on the more recent study. This latter view makes sense if the author is, say, a science reporter who has already written about the first study. In the end, the circumspect nature of the passage makes it unwise to infer that the author has taken sides. \par Choice~\TextChoice {1} is incorrect because the passage is not “primarily concerned with” examining the methodologies of the studies. Both studies’ methodologies are discussed briefly, but they are not the focus. Moreover, the passage does not highlight the flaws in one study or in one study’s methodology. \par Choice~\TextChoice {2} is wrong because the passage never suggests that the two studies are “in complete agreement.” In particular, the author states, “There remains the issue of reconciling Day’s results and conclusions with Milliken’s” (\reflines {ThereMillikens}). It is hard to conclude that the author believes the studies are “in complete agreement” if the “issue of reconciling” them “remains.” \par Choice~\TextChoice {3} is incorrect. The author does not argue in favor of a single conclusion. \par Choice~\TextChoice {4} is correct. The title of the piece, “‘Rusty Rock’ May Be Product of Dry Moon,” strongly suggests that the passage focuses on the Day study, and the bulk of the passage (\reflines {DayStudy1}, \reflines {DayStudy2}) deals with the Rusty Rock, Day’s study, or both. By contrast, only \reflines {MillikenStudy} deal solely with the Milliken study. The remainder of choice~\TextChoice {4} is accurate. Day’s study does call into question Milliken’s, and Milliken’s study was earlier and, at the time Day published, recent.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null