let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 44
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 2
let question = As presented in the passage, the conclusion that the interior of the moon is dry can best be described as
let choices = ['contradicted by all available evidence and studies.', 'theoretical but lacking empirical evidence.', 'widely held but called into question by some research.', 'undisputed and generally assumed in current research.']
let answer = C
let solution = Choice~\TextChoice {1} is incorrect because Day’s study supports the conclusion that the interior of the Moon is dry. \par Choice~\TextChoice {2} is incorrect because there is empirical evidence to support the conclusion. In particular, Day’s study, which concludes that the Moon is dry, relies on the Rusty Rock, which certainly can be described as “empirical evidence.” \par Choice~\TextChoice {3} is correct. The passage states that the view of a dry Moon is “nearly unanimous” (\reflines {NearlyUnanimous}), so it is certainly fair to state that the view is “widely held.” Since Milliken’s conclusion is that the Moon’s interior is wet, it is also safe to state that the conclusion to the contrary has been “called into question.” \par Choice~\TextChoice {4} is wrong because Milliken’s study certainly disputes the notion of a dry Moon. Whether the rest of choice~\TextChoice {4} is accurate is irrelevant, and this point is important. Essentially, choice~\TextChoice {4} says “X and~Y.” Both must be true for choice~\TextChoice {4} to be correct, and if X is false, the entire answer is false.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null