let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 46
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 3
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{ButWet} (“But a study \\Ellipsis wet”)', '\\reflines [Capital]{ForLeadWet} (“For lead \\Ellipsis wet”)', '\\reflines [Capital]{TheirFormation} (“Their \\Ellipsis formation”)', '\\reflines [Capital]{InOtherInterior} (“In other words \\Ellipsis interior”)']
let answer = C
let solution = Choice~\TextChoice {3} is correct. It cites the sentences relied on in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null