let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 47
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining implicit meanings
let difficulty = 1
let question = The passage indicates that the volcanic beads consists of structures that
let choices = ['hold water.', 'are unstable.', 'have terrestrial origins.', 'cannot be explained.']
let answer = A
let solution = In \reflines {CrystallineWater}, the author states that Milliken found that “crystalline formations within the beads contained water.” Choice~\TextChoice {1} is thus correct. There is no support in the passage for the other answer choices.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null