let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 48
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 3
let question = As used in \reflines {common}, “common” most nearly means
let choices = ['simple.', 'prosaic.', 'prevalent.', 'understood.']
let answer = C
let solution = The full context in which “common” occurs is “Analysis of clouds formed above oceans has shown that the clouds have a higher concentration of lighter oxygen isotopes than the oceans, in which heavier oxygen isotopes are common” (\reflines {AnalysisCommon}). The sentence indicates that the clouds have more lighter oxygen isotopes than the oceans and that the oceans have more heavier oxygen isotopes than the clouds. In this context, “common” most nearly means “prevalent.” Choice~\TextChoice {3} is correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null