let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 49
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Determining explicit meanings
let difficulty = 4
let question = For Day, the presence and type of zinc in the Rusty Rock were especially important because zinc
let choices = ['is especially easy to identify.', 'lasts longer than other elements in rocks.', 'is an element that evaporates readily.', 'is the most abundant element on the Moon.']
let answer = C
let solution = In \reflines {ToDayRock}, the passage states, “To Day, this fact suggests that during the Moon’s formation, zinc, a volatile element, evaporated, later condensing on the surface and becoming part of the Rusty Rock.” In this sentence, zinc is identified as “a volatile element.” Earlier, the passage tells us what “volatile” means: “meaning that it evaporates easily” (\reflines {MeaningEasily}). Choice~\TextChoice {3} is thus correct. The other answer choices are incorrect because they have no support in the passage.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null