let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 5
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 4
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{ApparentlyVisitors} (“Apparently \\Ellipsis visitors”)', '\\reflines [Capital]{SheWouldVisitors} (“She would \\Ellipsis visitors”)', '\\reflines [Capital]{HerGrandfatherDo} (“Her grandfather \\Ellipsis do”)', '\\reflines [Capital]{ThereSaw} (“There \\Ellipsis saw”)']
let answer = A
let solution = Choice~\TextChoice {1} is correct. It cites the sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null