let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 50
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 3
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{InParticularRock} (“In particular \\Ellipsis Rock”)', '\\reflines [Capital]{ToDayRock} (“To Day \\Ellipsis Rock”)', '\\reflines [Capital]{TheAnalysisIsotope} (“The analysis \\Ellipsis isotopes”)', '\\reflines [Capital]{ToThisBeads} (“To this end \\Ellipsis beads”)']
let answer = B
let solution = Choice~\TextChoice {2} is correct. It cites a sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null