let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 51
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Interpreting words and phrases in context
let difficulty = 2
let question = As used in \reflines {simple}, “simple” most nearly means
let choices = ['elementary.', 'naïve.', 'feeble.', 'mere.']
let answer = D
let solution = The full context in which “simple” occurs is “The results may be of more than simple theoretical value” (\reflines {TheResultsValue}). Of the answer choices, choice~\TextChoice {4} is best. The context is intended to indicate that the value goes beyond just theoretical, and in this sense, “mere” makes the most sense. \par Choice~\TextChoice {1} is the most plausible incorrect answer choice, but if “simple” meant “elementary,” then the implication would be that the ramifications of the study go beyond basic theory and into advanced theory. The passage makes clear, however, that the study is significant for a categorically different reason (money).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null