let tableName = TB12
let formCode = TB-12
let passageCode = pm-35
let questionNumber = 52
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing arguments/Analyzing claims and counterclaims
let difficulty = 5
let question = Day counters Milliken’s conclusion about the characteristics of the interior of the Moon by pointing out that Milliken and his team
let choices = ['relied on glass beads that are not typical of materials found on the lunar surface.', 'are unable to explain how glass beads with water content were created.', 'interpreted evidence in order to support preconceived notions.', 'focused on beads that were contaminated by the terrestrial atmosphere.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. In \reflines {CannotFormation}, the author quotes Day as saying that Milliken and his team “cannot elucidate the mechanism of their formation.” Choice~\TextChoice {2} paraphrases this statement. \par The other answer choices lack support in the passage. To be precise, the passage does not state that Day levied any of the charges in the three incorrect answer choices.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null