let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 6
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing purpose
let difficulty = 3
let question = The description of Bokamoso’s thoughts while she is in the hut mainly serves to
let choices = ['emphasize her growing sense of independence.', 'highlight the need for trade with outsiders.', 'suggest her lack of understanding of the intricacies of trade.', 'portray her ability to draw inferences from her observations.']
let answer = D
let solution = It helps to understand that the passage uses the third-person, limited POV and that everything is related through Bokamoso’s thoughts. In the relevant paragraph (\reflines {ApparentlyTradition}), she makes several deductions. She first deduces that the guests are unexpected in \reflines {ApparentlyVisitors}. She becomes aware that meat is cooking even though she cannot see the meat (since it is “inside the oven,” as indicated in \reflines {TheMeatOven}). Her grandfather merely nods, but she knows “what she must do” (\reflines {KnewDo}). Finally, she deduces from the fact that the meat is inside the oven that her grandfather has chosen to honor tradition (\reflines {SheUnderstoodTradition}). The common theme here is Bokamoso’s “ability to draw inferences from her observations.” Choice~\TextChoice {4} is correct. \par Choice~\TextChoice {1} is incorrect because the relevant paragraph does not indicate Bokamoso’s “growing sense of independence.” Indeed, nothing in the passage suggests that she is becoming more independent. There are several suggestions that she \emph {wants} to be more independent, but there is no indication that she is in fact achieving that goal. \par Choice~\TextChoice {2} is incorrect because Bokamoso’s deductions are unrelated to the importance of trade. We might try to justify this answer by pointing to her silence throughout the process and infer from that fact that she knows not to disturb her grandfather during something as important as negotiations. Such an inference, however, goes well beyond what the story actually says, and there are multiple other possibilities. It may be, for example, that Bokamoso is silent because her culture does not allow children to speak in the presence of adults unless specifically invited to do so. Inferring the importance of trade from her behavior simply goes beyond what the text actually implies. \par Choice~\TextChoice {3} is wrong. The best argument in favor of choice~\TextChoice {3} is that Bokamoso makes several deductions, though none of them is about the negotiation itself and that therefore she must be perceptive about the other things but not about the negotiations. However, we can respond to this argument by pointing out that Bokamoso \emph {does} understand some of the aspects, from the sharing of the stew to her grandfather’s use of the good bowls for the guests and his decision to eschew the metal pans. Simply put, assuming that the relevant paragraph is emphasizing her failure to understand the protocols of trading is stretching things far too far.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null