let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 7
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Rhetoric/Analyzing point of view
let difficulty = 3
let question = In the passage, Bokamoso views the San visits as
let choices = ['intrusive.', 'bothersome.', 'distressing.', 'unnecessary.']
let answer = D
let solution = Choice~\TextChoice {4} is correct. In \reflines {ThereWasTrade}, the passage states that Bokamoso has told her grandfather that “[t]here [is] no need for the family to trade.” Since the San are essentially synonymous with trade to her, Bokamoso regards their visits as unnecessary.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null