let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 8
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Reading closely/Using analogical reasoning
let difficulty = 4
let question = Kungawo would be most critical if Bokamoso wanted to do which of the following?
let choices = ['Make a journey to the city', 'Participate in the preparation of a meal', 'Observe him negotiate a trade', 'Speak directly to the San visitors']
let answer = A
let solution = Choice~\TextChoice {1} is correct. Though it is not necessary for the question that Bokamoso want to visit the city, she does seem to be curious: “Not that she was in any hurry to join the future. There was no reason to. But still, she would have liked to see” (\reflines {NotThatSee}). If Bokamoso were to indicate a desire to see the city, her grandfather likely would object. After all, she expresses the desire to travel to get mongongo nuts, but the passage tells us, “But when she made these requests, Kungawo simply shook his head with a smile and explained that there was no need for her to risk traveling anywhere” (\reflines {ButWhenAnywhere}). It is true that he offers another reason (“Besides, since they had goats, the mongongo nuts came to them,” \reflines {BesidesThem}), but the use of “Besides” suggests that this reason is secondary. \par Choice~\TextChoice {2} and choice~\TextChoice {3} are both wrong because the passage indicates that Bokamoso does both things. In \reflines {SheWentFood} she tends to the food, and in \reflines {TheyAllNegotiated}, everyone eats together during the negotiations. \par Choice~\TextChoice {4} is incorrect. The passage does not indicate that Bokamoso speaks to the San visitors, but neither does it say that she does not or that she is forbidden to do so.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null