let tableName = TB12
let formCode = TB-12
let passageCode = pm-36
let questionNumber = 9
let problemSetNumber = 1
let test = SAT
let subject = Reading
let category = Information and Ideas/Citing textual evidence
let difficulty = 3
let question = Which choice provides the best evidence for the answer to the previous question?
let choices = ['\\reflines [Capital]{KungawoWouldCharge} (“Kungawo \\Ellipsis charge”)', '\\reflines [Capital]{KungawoCountedKraal} (“Kungawo \\Ellipsis kraal”)', '\\reflines [Capital]{TheirVisitsAny} (“Their visits \\Ellipsis any”)', '\\reflines [Capital]{ButWhenAnywhere} (“But when \\Ellipsis anywhere”)']
let answer = D
let solution = Choice~\TextChoice {4} is correct. It cites the sentence relied upon in the solution for the previous question.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null