let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 1
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Syntax
let difficulty = 3
let question = Which choice most effectively combines the sentences at the underlined portion?
let choices = ['adhesion,” creating a category of contracts that', 'adhesion” and', 'adhesion,” though such a contract', 'adhesion,” and this type of contract']
let answer = B
let solution = Choice~\TextChoice {2} is correct. It offers the most concise means of combining the sentences and preserves the meaning of the original. \par Choice~\TextChoice {1} is incorrect. It is far wordier than choice~\TextChoice {2} and adds no meaning. (That there is a “category” is established earlier in the sentence.) \par Choice~\TextChoice {3} is incorrect. This answer choice suggests that the name is improper and creates an overall awkwardness in the sentence with the two contrast words (“though” and “although”). \par Choice~\TextChoice {4} is incorrect. It is far wordier than choice~\TextChoice {2} and adds no meaning.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null