let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 10
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Sentence boundaries
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'terms, besides, they', 'terms;', 'terms and']
let answer = D
let solution = Choice~\TextChoice {1} is wrong. It preserves a comma splice. \par Choice~\TextChoice {2} is wrong. The addition of “besides” does not fix the original comma splice. (There are some who would disagree that choice~\TextChoice {2} creates a comma splice. They would argue instead that the result is a fused or run-on sentence since two main clauses are joined without commas. The commas in this case would be argued to offset “besides” but not to join the clauses. Even with this interpretation, the result is an error.) \par Choice~\TextChoice {3} is incorrect. The portion after the semicolon is not a main clause. \par Choice~\TextChoice {4} is correct. It uses the coordinating conjunction “and” to join the predicates “do not read the terms” and “wouldn’t understand or agree to them if they did.” The change in tense does not create an error.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null