let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 11
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Development/Quantitative information
let difficulty = 4
let question = At this point, the writer is considering adding the following sentence. \begin {quote} In fact, according to the data in the graph, most American adults take no steps to protect their privacy online at all, making clear terms of service even more important. \end {quote} Should the writer make this addition here? \par \begin {tikzpicture} \begin {axis}[title={Percent of Adults Employing Privacy Measures Online,~2013}, floating xbar, width=4.75cm, height=6.5cm, ymin=1, ymax=8, ytick={1,...,8}, enlarge y limits={abs=0.25cm}, yticklabels={clear cookies/browser, disable cookies, post anonymous comments, mask identity, use public computer, use fake name, encrypt communications, use anonymous browser }, y dir=reverse, y tick label style={align=flush right, text width=11em }, xmin=0, xmax=80, xtick=\empty , nodes near coords={\pgfmathprintnumber \pgfplotspointmeta \%} ] \addplot [fill=gray] coordinates {(64,1) (41,2) (25,3) (18,4) (18,5) (18,6) (14,7) (14,8) }; \end {axis} \PrintPassageDiagramCaptionTikz {Source: Pew Research Center} \end {tikzpicture}
let choices = ['Yes, because it connects the importance of clear terms of service to most American adults’ Internet browsing habits.', 'Yes, because it underscores the urgency of making sure that terms of service are short and fair.', 'No, because the issue of American adults’ use of the Internet is irrelevant to the main point of the passage.', 'No, because it is not an accurate interpretation of the data in the graph.']
let answer = D
let solution = The only issue of importance here is the fact that the sentence contradicts the graph. According to the graph, approximately 64~percent of US adults cleared their cookies and browser history. Since 64~percent is more than half, it is inaccurate to say that “most American adults take no steps to protect their privacy online at all.” Choice~\TextChoice {4} is thus correct. \par Choice~\TextChoice {3} might be attractive to some students, particularly since the graph itself fairly clearly diverges from the main point of the passage. But the wording of this answer choice is far too strong. The passage as a whole is about the Internet, and so it is inaccurate to state that “the issue of American adults’ use of the Internet is irrelevant to the main point of the passage.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null