let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 12
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Development/Quantitative information
let difficulty = 3
let question = Which choice best reflects the information provided in figures 1 and~2?
let choices = ['NO CHANGE', 'was higher in every year from 2002 to~2015 than it was in~2001, with males more likely than females', 'remained essentially constant from 2002 to~2015, with males and females equally likely', 'generally increased from 2001 to~2015, with females more likely than males']
let answer = B
let solution = Figure~1 shows that the number of cases of Lyme disease in the US decreased in several years (from 2002 to~2003, from 2003 to~2004, from 2005 to~2006, and from 2009 to~2010, for example). Choice~\TextChoice {1} is thus incorrect. \par Figure~1 shows that the number of cases of Lyme disease was indeed higher in every year from 2002 to~2015 than it was in~2001. In~2001, the number was approximately~\num {17000}, and in no other year in the graph was the level that low. We can verify this point by drawing a horizontal line through the dot corresponding to~2001 and seeing that all other points are above the line. Figure~2 shows that, for each of the five age groups, the number of males infected exceeded the number of females infected. While we certainly can estimate the 10~numbers for Figure~2, we have no need to do so. Since the number of males is larger in every group, the overall number of males must be greater. Choice~\TextChoice {2} is thus correct. \par Choice~\TextChoice {3} is incorrect because both of its claims are incorrect. We can, perhaps, debate the issue of whether the number of cases of Lyme disease remained “essentially constant,” but even if we grant that a nearly 78~percent increase (from 2001 to~2009) is “essentially constant,” the numbers of males and females infected are clearly different. \par Choice~\TextChoice {4} is wrong because females were not more likely than males to contract Lyme disease, according to Figure~2. That figure shows that males in each age category accounted for more cases of Lyme disease than did females.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null