let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 13
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Unnecessary punctuation
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'means, for the spread of Lyme disease to humans,', 'means for the spread of Lyme disease to humans', 'means: for the spread of Lyme disease to humans']
let answer = C
let solution = There is no need for any punctuation, so choice~\TextChoice {3} is correct. \par Choice~\TextChoice {1} is incorrect because it uses a comma to separate the subject from the verb. \par Choice~\TextChoice {2} is incorrect because it treats the prepositional phrase “for the spread of Lyme disease to humans” as a non-restrictive phrase. But that information is necessary. Otherwise, “means” is unclear. \par Choice~\TextChoice {4} is incorrect because the portion before the colon is not a clause.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null