let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 14
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Usage/Agreement/Subject-verb agreement
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'are', 'to be', 'have been']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The head of the noun phrase that serves as the subject is “presence,” singular. We thus need a singular verb.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null