let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 15
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Logical sequence
let difficulty = 4
let question = To make this paragraph most logical, sentence~6 should be placed
let choices = ['where it is now.', 'after sentence~2.', 'after sentence~3.', 'after sentence~4.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. Sentence~3 refers to “the final stage,” but there is no prior mention of stages. Only choice~\TextChoice {2} puts the sentence in question, which introduces the four stages of ticks’ lives, before the mention of “the final stage.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null