let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 16
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Precision
let difficulty = 1
let question = null
let choices = ['NO CHANGE', 'predators of', 'terrors to', 'adversaries of']
let answer = B
let solution = Choice~\TextChoice {2} is correct. It uses the simplest, most direct wording. The other answer choices either lack the precise meaning or fail to maintain the objective tone of the passage.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null