let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 18
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Precision
let difficulty = 4
let question = null
let choices = ['NO CHANGE', 'urgent', 'censorious', 'critical']
let answer = D
let solution = Choice~\TextChoice {4} is correct. The full context, “These numbers are [correct answer] because of the life cycle of ticks and the related cycle for Lyme disease,” makes it clear that we want a word meaning something like “important.” Choice~\TextChoice {1} is incorrect because “dire” has a clear connotation of danger or something else negative. But the numbers are encouraging, certainly not “dire.” Choice~\TextChoice {2} is incorrect because there is no suggestion that time is a vital issue. Choice~\TextChoice {3} is incorrect because “censorious” means “critical” in a different context.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null