let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 19
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Introductions, conclusions, and transitions
let difficulty = 3
let question = Which choice provides the best transition from the previous paragraph?
let choices = ['NO CHANGE', 'Despite the view of mice as pests,', 'Although ticks are loathed as human parasites,', 'Before parasitizing humans,']
let answer = A
let solution = The previous paragraph ends with the sentence “These numbers are [critical] because of the life cycle of ticks and the related cycle for Lyme disease among ticks.” This paragraph contains five sentences. The first two explain the life cycle of ticks as they progress from smaller to larger hosts. The second through fourth discuss how ticks get the agent that they later transmit to humans, the agent that causes Lyme disease. (The fifth summarizes the paragraph.) \par Choice~\TextChoice {1} is correct because it implicitly refers to the two cycles (by referencing “the first cycle”) and because the single-cycle reference feeds into the first sentence of this paragraph, whose first sentence is about the life cycle of the tick, the first of the two cycles. \par Choice~\TextChoice {2} is incorrect because the view of mice as pests is completely beside the point for this paragraph. Moreover, beginning the sentence with “Despite the view of mice as pests” is simply bizarre, suggesting that you’d think that ticks would have better taste. \par Choice~\TextChoice {3} is incorrect. It makes no reference to the previous paragraph and suggests, like choice~\TextChoice {2}, that ticks are demonstrating poor judgment skills in choosing to feed on mice. \par Choice~\TextChoice {4} is incorrect because it makes no reference to the previous paragraph. “Before parasitizing humans” is a fine beginning to the sentence, but the question specifically asks for a transition, and this answer choice does not provide one.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null