let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 2
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Parallel structure
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'clicking on', 'then we click on', 'DELETE the underlined portion.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The sentence provides a list of three things, the first two of which are “encountering such contracts” and “failing to read them.” For parallelism, the third item in the list should be “clicking on ‘accept’ anyway.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null