let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 20
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Within-sentence punctuation
let difficulty = 4
let question = null
let choices = ['NO CHANGE', 'humans, fewer cases,', 'humans; fewer cases', 'humans—fewer cases,']
let answer = A
let solution = There are two issues in this question. The first is the type of punctuation after “humans,” and the second is whether there should be a comma after “cases.” We’ll take the second issue first. There is no reason for a comma between the noun and the preposition any more than there is after “States” in “United States of America.” \par The first issue is more complex. Based on the structure of the sentence, in which “fewer cases of Lyme disease” is the “good news for humans,” we can use a comma, a dash, or a colon. Because choice~\TextChoice {1} is the only answer choice that uses the right punctuation the first time and omits the comma after “cases,” it is correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null