let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 21
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Sentence boundaries
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'present; we', 'present. We', 'present—we']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The short explanation is that the phrase “by introducing or reintroducing predators into the environment where \emph {Borrelia} bacteria are present” should be followed by a comma. The longer explanation accounts for the fact that the sentence does not begin with “by.” Rather, the sentence begins with “What Hofmeester’s study suggests is that.” However, this beginning does not change the analysis. In such a context, wherein “that” acts as a conjunction, transforming the clause “by introducing or reintroducing predators into the environment where \emph {Borrelia} bacteria are present, we can reduce both the number of ticks and the incidence of the spread of Lyme disease” into a noun phrase, the analysis of the clause proceeds in the same way it would if the clause were not preceded by the conjunction.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null