let tableName = TB12
let formCode = TB-12
let passageCode = pm-25
let questionNumber = 22
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Parallel structure
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'to feed', 'feed', 'would feed']
let answer = C
let solution = The relevant clause is “The result, he believes, is that young ticks fail to find sustenance (and thus perish) or else [correct answer] on animals like birds that do not carry the bacteria.” For parallelism, the word that goes into the square brackets should match “fail,” a present-tense verb. Choice~\TextChoice {3} is thus correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null