let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 23
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Usage/Conventional expression
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'for', 'on', 'to']
let answer = C
let solution = Choice~\TextChoice {3} is correct. We want to say that Picasso worked \emph {on} the mural (or, as the case is, didn’t work on it). After “work” in this context, “on” is the correct preposition.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null