let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 24
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Sentence boundaries
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'they were acting', 'which were acting', 'acting']
let answer = D
let solution = Choice~\TextChoice {4} is correct. The use of “acting” in this context creates a present-participial modifier. This modifier, coming after “planes from Nazi Germany bombed the Basque town of Guernica” and following a comma, means that the modifier refers to “planes.” \par Choice~\TextChoice {1} is incorrect. The use of “acted” is awkward here. It would appear that “acted at the behest of the Spanish Nationalists” functions as a predicate and, coming after the comma and, before that, a predicate (“bombed the Basque town of Guernica”) with a past-tense verb, forms the second item in a list. But there is no third item and no conjunction to join the two items. The result is something that may be stylistically acceptable in certain writing but is incorrect on the Writing and Language portion of the SAT. \par Choice~\TextChoice {2} is incorrect. It creates a comma splice. \par Choice~\TextChoice {3} is incorrect because the resultant relative clause (“which were acting at the behest of the Spanish Nationalists”) would seem to modify “the Basque town of Guernica.” The result is both an illogical meaning and a subject-verb mismatch (since “which” becomes singular as a result of its antecedent’s number).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null