let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 25
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Concision
let difficulty = 1
let question = null
let choices = ['NO CHANGE', 'opposed and fought against', 'fought in opposition against', 'fighting against and opposing']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The other three answer choices add words but not meaning, so, as a matter of concision, choice~\TextChoice {1} is best.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null