let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 26
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Style and tone
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'cause a ton of terror.', 'totally terrify the people.', 'bring terror like never before.']
let answer = A
let solution = The issue is one of tone and style. Choice~\TextChoice {1} is correct because it is the most formal and fits well with the style of the passage as a whole. Choice~\TextChoice {2} is incorrect primarily because of the words “a ton of,” which are unnecessarily informal or colloquial. Choice~\TextChoice {3} is incorrect primarily because of the word “totally,” which is excessively colloquial. Choice~\TextChoice {4} is excessively informal. Moreover, the words “like never before” seem unnecessary in that they raise issues that arguably weaken the claim (by inviting comparisons to the history of human suffering).
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null