let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 27
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Logical sequence
let difficulty = 4
let question = To make this paragraph most logical, sentence~4 should be placed
let choices = ['where it is now.', 'before sentence~1.', 'after sentence~1.', 'after sentence~5.']
let answer = C
let solution = Choice~\TextChoice {3} is correct. The sentence in question states that “[t]his conversion, however, was not immediate.” The key word is “this.” We need a reference to a “conversion” before this sentence. That reference occurs in sentence “When news reached Picasso, he scrapped his original plans for the mural,” which is the first sentence in the paragraph. The act of scrapping the original plans represents the conversion. Choice~\TextChoice {2} is thus incorrect. \par To establish that choice~\TextChoice {3} is correct (rather than choice~\TextChoice {1} or choice~\TextChoice {4}), however, requires more insight. The preceding paragraph makes the claim that the sentence in question must come after sentence~1, but that claim does not establish that it must come \emph {immediately} after sentence~1. However, the claim in the sentence, that the conversion was not immediate, leads well into sentences 2 and~3. The best placement is thus after sentence~1, where the general claim that the conversion was not immediate can lead into the specific evidence in sentences 2 and~3.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null