let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 28
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Usage/Pronouns/Pronoun clarity
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'the painting measured over 11~feet tall by 25~feet wide.', 'over 11~feet tall and 25~feet wide was what it measured.', 'they were more than 11~feet in height and 25~feet in width.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. Choices~\TextChoice {1}, \TextChoice {3}, and~\TextChoice {4} are all incorrect because they have pronouns (“their,” “it,” and “they,” respectively) that lack antecedents.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null