let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 29
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Development/Support
let difficulty = 3
let question = Which choice gives a reason to support the claim that the images in Guernica differ from those that might be found in a realistic painting?
let choices = ['NO CHANGE', 'was the style of painting with which Picasso was most associated,', 'was a style used not just for painting but also for sculpture,', 'is characterized by geometric, often abstract, shapes,']
let answer = D
let solution = We want to “support the claim that the images in Guernica differ from those that might be found in a realistic painting.” Choice~\TextChoice {4} is correct because it provides the clearest reason why cubism differs significantly from realism.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null