let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 3
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = ['Standard English Conventions/Conventions of Usage/Agreement/Subject-verb agreement', 'Standard English Conventions/Sentence structure/Inappropriate shifts in construction/Verb tense, mood, and voice']
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'is', 'has been', 'had been']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The full sentence reads “Those of iTunes run over 17~pages, while eBay’s [answer] about 18~pages long.” Without referring to previous sentences, we can recognize that something has been omitted after “eBay’s” here. The omission relates to the use of “Those” before “of iTunes,” so the omission must also be plural. (We have to be a tiny bit careful here. It is possible to elide without preserving number. It might be possible to write something like “My sisters are all in college while Brad’s \emph {is} still in elementary school” if Brad has a single sister. Some would object to that structure, though. At any rate, there is no need for such caution here. “Those” refers to “terms of service” in either the preceding sentence as the passage is written or the preceding sentence after sentence~6 is moved to its proper spot.)
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null