let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 30
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Inappropriate shifts in construction/Verb tense, mood, and voice
let difficulty = 5
let question = null
let choices = ['NO CHANGE', 'bears', 'had borne', 'will bear']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The sentence begins with “A horse seems to trample a soldier,” which uses the present-tense “seems.” Choice~\TextChoice {2} is the only answer choice that maintains the present tense and the time reference. (Choice~\TextChoice {4} uses the present tense but refers to the future, not the present.)
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null