let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 31
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Development/Support
let difficulty = 3
let question = The writer is considering deleting the underlined sentence. Should the sentence be kept or deleted?
let choices = ['Kept, because it provides evidence to support the earlier claim that previous artists had hidden images in art.', 'Kept, because it emphasizes a particular symbol that has historically been common in most styles of painting.', 'Deleted, because it suggests that Picasso deliberately mimicked an older style of painting.', 'Deleted, because it fails to explain why both Holbein and Picasso would include skulls hidden in paintings.']
let answer = A
let solution = The preceding sentence states, “Paintings had certainly hidden images before.” This sentence, with a specific reference, offers evidence to support that claim. Choice~\TextChoice {1} is thus correct. \par Choice~\TextChoice {2} is incorrect because the sentence does not establish or suggest that skulls (the “particular symbol”) have been “common in most styles of painting.” Two examples do not suffice. \par Choice~\TextChoice {3} is incorrect because the sentence merely offers an example of a hidden image. It does not suggest that Picasso “deliberately mimicked” Holbein or even knew about Holbein. However, for the sake of argument, let us assume that the passage does intend to indicate that Picasso was intentionally derivative. Surely, the previous sentence (“Paintings had certainly hidden images before”) already advances that claim. If anything, the sentence in question merely identifies the particular source for Picasso’s inspiration or mimicry. \par Choice~\TextChoice {4} is incorrect. It is certainly true that the sentence does not specify why Picasso and Holbein would include skulls. It is also true that the sentence does not specify why so many Americans enjoy baseball. The point here is that there is no need to explain why skulls are present in \emph {both} works. The reason for the presence of the skull in \emph {Guernica} is implicit from the passage. The reason for the presence of one in \emph {The Ambassadors} is beside the point for a passage about Picasso’s Guernica.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null