let tableName = TB12
let formCode = TB-12
let passageCode = pm-23
let questionNumber = 32
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Usage/Possessive determiners
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'it’s', 'they’re', 'their']
let answer = D
let solution = The appositive in which the word occurs is “apparently random geometric figures that only on close inspection yield its secret.” Since the antecedent for the pronoun is “figures,” we need a plural pronoun. Choices~\TextChoice {1} and~\TextChoice {2} are thus incorrect. (Note, however, that the singular “secret” is correct. The shapes combine for a single secret, namely the bull.) Of the remaining choices, choice~\TextChoice {3} is incorrect because “they’re” is short for “they are,” which does not fit the context. We want the possessive “their,” and choice~\TextChoice {4} is thus correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null