let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 34
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Introductions, conclusions, and transitions
let difficulty = 2
let question = Which choice provides the best introduction to the passage?
let choices = ['NO CHANGE', 'During tough economic times, many people are just happy to have jobs, even if they are not their dream jobs.', 'For a wide variety of people, a style of work that has been around since the~1940s is proving valuable.', 'According to the US Bureau of Labor Statistics, unemployment in~2016 remained relatively stable at 4.3~percent.']
let answer = C
let solution = Choice~\TextChoice {1} is wrong because the passage is not about the change technological advances have brought to the workplace. The passage does discuss changes in the way temporary agencies have supplied employees, but the two changes are not sufficiently close to make choice~\TextChoice {1} a good introduction. \par Choice~\TextChoice {2} is not correct. The passage is not really about “tough economic times,” and the sentence only barely alludes to temporary work. \par Choice~\TextChoice {3} is correct. The passage mentions that temporary work has been around since the~1940s, so the reference in this sentence to that decade is accurate and appropriate. Moreover, the reference to “a wide variety of people” in the sentence in choice~\TextChoice {3} fits well with the next sentence’s reference to “high-school students, college students, and even recent college graduates” and “more established workers.” Finally, the sentence does lead into the general point of the passage, namely that temporary work can be a solution for a wide variety of people. \par Choice~\TextChoice {4} is incorrect. The passage is not about the unemployment rate, and information about it, while undeniably relevant, does not serve as a good introduction to the passage.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null