let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 35
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Nonrestrictive and parenthetical elements
let difficulty = 1
let question = null
let choices = ['NO CHANGE', 'people', 'people:', 'people—']
let answer = D
let solution = Choice~\TextChoice {4} is correct. The phrase “including high-school students, college students, and even recent college graduates” is a parenthetical phrase set off by an em dash after “graduates” and thus needs an em dash before “including.”
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null