let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 36
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Within-sentence punctuation
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'value. In', 'value: in', 'value, in']
let answer = A
let solution = Choice~\TextChoice {1} is correct. There is no need for any punctuation here. The prepositional phrase “in temporary employment” is necessary to explain where people find value, and any punctuation in between “value” and “in” serves no purpose. \par Choice~\TextChoice {2} is incorrect because it leads to fragment (“In temporary employment”). \par Choice~\TextChoice {3} is incorrect. A colon should follow not only a complete main clause but also a complete thought. Here, “more established workers are also finding value” does not complete the thought. In essence, the objection to this answer choice is essentially the point raised for choice~\TextChoice {1}, namely that “in temporary employment” is a necessary part of the clause. \par Choice~\TextChoice {4} is wrong because the phrase “in temporary employment” is an integral part of the clause.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null