let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 37
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Precision
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'Similarly,', 'However,', 'Eventually,']
let answer = D
let solution = The paragraph begins by making the general claim that “There was a time when temporary employment agencies were associated almost exclusively with the Kelly Girl.” The second sentence backs up in time to give us a bit of history, namely the beginning of Russell Kelly Office Service’s act of supplying temporary office workers. The third sentence elaborates on that practice. The fourth sentence, without the transition, states, “temporary work became nearly synonymous with office help.” \par Choice~\TextChoice {1} is incorrect because it indicates that “temporary work became nearly synonymous with office help” for the purpose of the practice of supplying temporary office staff. Clearly, the author’s intent is to indicate that the practice became so widespread that people associated temporary work with work in offices. \par Choice~\TextChoice {2} is incorrect because the third and fourth sentences of the paragraph are not making similar claims. \par Choice~\TextChoice {3} is incorrect because the fourth sentence does not present a contrast. \par Choice~\TextChoice {4} is correct because it fits with the chronology. With this answer choice, the second, third, and fourth sentences present a logical sequence of events.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null