let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 38
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Usage/Agreement/Pronoun-antecedent agreement
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'a temp agency was usually called by them.', 'that company would usually call a temp agency.', 'those were usually calls to a temp agency.']
let answer = C
let solution = Since the sentence begins with “If a company that sells handicraft supplies needed an annual inventory,” choices \TextChoice {1} and~\TextChoice {2} are incorrect because they use plural pronouns (“they” and “them”) for a singular antecedent (“a company”). Choice~\TextChoice {4} is incorrect because “those” lacks an antecedent. \par Thus, choice~\TextChoice {3} must be correct—and it is. This answer choice avoids problems with pronoun reference by avoiding pronouns altogether.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null