let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 39
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Precision
let difficulty = 4
let question = null
let choices = ['NO CHANGE', 'appropriate', 'specialized', 'exceptional']
let answer = C
let solution = The sentence in which the word appears is “Agencies still exist for motivated young people with few skills, but there are also agencies that cater to highly [correct answer] fields.” The sentence establishes a contrast by using “but,” so we clearly want a word that contrasts with fields in which “few skills” are required. \par Choice~\TextChoice {3} is correct. The description of a field as “specialized” presents a strong contrast between such a field and one that requires “few skills.” \par Choice~\TextChoice {1} is incorrect. The word “particular” means “of, belonging to, or associated with a specific person, group, thing, or category; not general or universal: \emph {She did not have a particular café in mind for their get-together},” “distinctive among others of the same group, category, or nature; noteworthy or exceptional: \emph {an area known for its particular style of architecture},” “of, relating to, or providing details; precise: \emph {gave a particular description of the incident},” “attentive to or concerned with details or niceties, often excessively so; fussy,” or “Encompassing some but not all of the members of a class or group. Used of a proposition,” according to \emph {The American Heritage Dictionary of the English Language, Fifth Edition}. These meanings do not fit well for the context. \par Neither of the other two answer choices fits the context well.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null