let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 4
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Concision
let difficulty = 2
let question = null
let choices = ['NO CHANGE', 'intimidating and scary:', 'frightening, intimidating:', 'dauntingly intimidating:']
let answer = A
let solution = Choice~\TextChoice {1} is correct. The other three answer choices add words that are redundant or unnecessary. While it may be possible in some cases to distinguish “intimidating” from either “scary” or “frightening,” in the context of long terms of service, adding either “scary” or “frightening” does not produce any significantly different or more precise meaning. Choices \TextChoice {2} and~\TextChoice {3} are thus incorrect. Choice~\TextChoice {4} is incorrect because “daunting” means “intimidating,” so there is a true issue of redundancy here.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null