let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 40
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Syntax
let difficulty = 3
let question = Which choice best combines the sentences at the underlined portion?
let choices = ['individuals, and these employees can', 'individuals to', 'individuals, so the employer can benefit from employees able to', 'individuals when there is a need for people to']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The other three answer choices use more words but do not add meaning to the sentence. Since they do not add any meaning, those extra words are not necessary, and the most economical choice is best.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null