let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 41
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Sentence structure/Sentence formation/Modifier placement
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'students can find paid work.', 'it is possible for students to find paid work.', 'paid work may be obtained by students.']
let answer = B
let solution = Choice~\TextChoice {2} is correct. The sentence begins with the modifier “Faced with greater free time during summer months,” so the head of the noun phrase following the modifier must be the thing modified. Only choice~\TextChoice {2} supplies “students” as that word. The other three answer choices result in a dangling modifier.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null