let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 42
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Introductions, conclusions, and transitions
let difficulty = 3
let question = Which choice best sets up the points raised in the next sentence?
let choices = ['NO CHANGE', 'Temporary employment offers variety since employees are rarely at the same job for long.', 'Temp agencies are generally happy to work around their workers’ schedules for reliable employees.', 'Temporary workers are generally paid by the temp agency, not directly by the employers on whose premises they work.']
let answer = A
let solution = The sentence after this one states, “Benefits, such as retirement planning and health insurance, for part-time work are generally either not available or are substantially less than given by full-time work.” We thus want something that transitions to the idea that there are some drawbacks to temporary work. Choice~\TextChoice {1} is correct because it offers just such a statement.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null