let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 43
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = ['Standard English Conventions/Conventions of Usage/Agreement/Pronoun-antecedent agreement', 'Standard English Conventions/Conventions of Usage/Logical comparison']
let difficulty = 4
let question = null
let choices = ['NO CHANGE', 'those associated with', 'that from', 'DELETE the underlined portion.']
let answer = B
let solution = If we consider the sentence using choice~\TextChoice {4} (that is, deleting the underlined portion), we have “Benefits \Ellipsis are substantially less than full-time work.” This choice results in an illogical comparison. Choice~\TextChoice {4} is thus incorrect, and choice~\TextChoice {3} is wrong for a similar reason, the comparison of a plural (“Benefits”) to a singular (“that”). Choice~\TextChoice {1} is wrong because it results in a comparison of a noun (“Benefits”) to a participial phrase (“given by \Ellipsis ”). Choice~\TextChoice {2} is correct because it compares a plural to a plural.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null