let tableName = TB12
let formCode = TB-12
let passageCode = pm-24
let questionNumber = 44
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Introductions, conclusions, and transitions
let difficulty = 3
let question = Which choice creates the best transition from the previous sentence to the next part of this sentence?
let choices = ['NO CHANGE', 'Although it does not happen in every case,', 'Since employers sometimes have greater needs than they first realize,', 'If they perform their jobs diligently and professionally,']
let answer = D
let solution = The previous sentence states, “Employees who work for temp agencies should remember that each new job is a potential interview and the chance to impress a possible future employer.” The end of this sentence states, “temp workers may find that their reward at the end of the temporary period is the offer of permanent employment.” \par Choice~\TextChoice {1} is incorrect. It creates a dichotomy between those who want nothing more than temporary work and those who seek something more. The problem with this dichotomy is that one of the groups (those who are content with temporary work) is not addressed by the previous sentence. \par Choice~\TextChoice {2} and choice~\TextChoice {3} are incorrect. Both offer transitions that could fit in the sentence, but neither transition is as effective as that in choice~\TextChoice {4}. \par Choice~\TextChoice {4} is correct. Moving from considering a job as an audition to performing diligently and professionally to securing a full-time job makes sense.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null