let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 5
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Organization/Logical sequence
let difficulty = 3
let question = To make this paragraph most logical, sentence~6 should be placed
let choices = ['where it is now.', 'before sentence 1.', 'after sentence~3.', 'after sentence~4.']
let answer = C
let solution = Choice~\TextChoice {3} is correct. Sentence~3 reads, “Many sites have terms of service that are extraordinarily long.” The sentence we are contemplating begins with “For example” and then offers two examples of long terms of service. Thus, the sentence in question is best placed after sentence~3. \par Choice~\TextChoice {4} is incorrect. While it is perfectly reasonable to debate the order of the examples (Facebook and YouTube in once sentence versus iTunes and eBay in another), the inclusion of “For example” in the sentence we are considering moving makes placement of that sentence after sentence~4 awkward.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null