let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 6
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Nonrestrictive and parenthetical elements
let difficulty = 1
let question = null
let choices = ['NO CHANGE', 'day', 'day:', 'day,']
let answer = D
let solution = The phrase “every day” is followed by a comma, indicating that it should be offset by commas on both sides. Choice~\TextChoice {4} is therefore correct.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null