let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 7
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Effective language use/Precision
let difficulty = 3
let question = null
let choices = ['NO CHANGE', 'Nonetheless,', 'Despite this,', 'Not surprisingly,']
let answer = D
let solution = The preceding sentence states that it would take 40~minutes every day for us to read the terms of service of the sites we use. This sentence states that most people do not read those terms of service. We want a transition that connects these two thoughts. \par Choices \TextChoice {1}, \TextChoice {2}, and~\TextChoice {3} are wrong because each indicates that there is a contradiction or contrast of some sort. There is none here. \par Choice~\TextChoice {4} is correct. If the time to read the terms of service is excessive, it should come as no surprise that most people do not read them.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null