let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 8
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Standard English Conventions/Conventions of Punctuation/Items in a series
let difficulty = 1
let question = null
let choices = ['NO CHANGE', 'understandable: and', 'understandable, and', 'understandable; and']
let answer = C
let solution = Choice~\TextChoice {3} is correct. In a list of items, the proper punctuation is a comma before (not after) the conjunction preceding the final term. (There are two points to note. The first is that the comma, called the Oxford comma, is optional but is used on the SAT. The second is that there are times when semicolons are permissible if the items in the list themselves have commas in them, but this sentence does not present such an instance.)
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null