let tableName = TB12
let formCode = TB-12
let passageCode = pm-22
let questionNumber = 9
let problemSetNumber = 2
let test = SAT
let subject = Writing and Language
let category = Expression of Ideas/Development/Support
let difficulty = 2
let question = Which phrase most effectively sets up the examples in the next two sentences?
let choices = ['NO CHANGE', 'how much of our free time we spend online.', 'the ways websites may use and gather our information.', 'the number of websites most of us use every day.']
let answer = C
let solution = The next sentence states, “Websites for posting photographs should not be entitled to use those photographs however they want,” and the one after it says, “Social-networking websites should be clear about whether they intend to track users, even off site.” Choice~\TextChoice {3} is correct because the first of these two sentences deals with using information (in the form of the photographs people upload) and the second discusses gathering information (in the form of tracking users). \par Choice~\TextChoice {1} is wrong because the two examples have nothing to do with users’ ages. \par Choice~\TextChoice {2} is wrong because the two examples do not relate to the time we spend online. \par Choice~\TextChoice {4} is wrong because the examples do not relate to “the number of websites most of us use every day.” The examples cite two different types of sites but do not state that these two represent a large number of sites or that all users use such sites.
let diagram = null
let choicesAlign = null
let calculator = null
let multipleQuestion = null
let diagramPostText = null
let diagramPreText = null
let percent_correct = null